services:
    app:
        container_name: ${APP_NAME}
        build: ../boiler_template_laravel/docker_base/docker
        volumes:
            - ./:/var/www/html
        ports:
            - 80:80
        environment:
            DB_CONNECTION: ${DB_CONNECTION}
            DB_HOST: ${DB_HOST}
            DB_PORT: ${DB_PORT}
            DB_DATABASE: ${DB_DATABASE}
            DB_USERNAME: ${DB_USERNAME}
            DB_PASSWORD: ${DB_PASSWORD}
    mysql:
        image: mysql:8.0
        volumes:
            - ./docker_base/db-data/:/var/lib/mysql
        ports:
            - 3306:3306
        environment:
            MYSQL_DATABASE: ${DB_DATABASE}
            MYSQL_ROOT_PASSWORD: 'root'
    phpmyadmin:
        image: phpmyadmin:latest
        ports:
            - 9090:80
        environment:
            PMA_HOST: mysql
            PMA_USER: ${DB_USERNAME}
            PMA_PASSWORD: ${DB_PASSWORD}
        depends_on:
            - mysql
